In [27]:
import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest

In [17]:
def check_outlier_by_column(column_values=None, df_data=None, name_column=None):
    q1 = np.quantile(column_values, .25)
    q3 = np.quantile(column_values, .75)

    iqr = q3-q1

    lower = q1 - 1.5*iqr
    higher = q3 + 1.5*iqr

    array_data = []

    number_outlier = 0
    number_not_outlier = 0

    for index in df_data.index:
        value = df_data[name_column][index]

        if value>higher or value< lower:
            array_data.append(1)
            number_outlier+=1
        else:
            array_data.append(0)
            number_not_outlier+=1
    
    return array_data, number_outlier, number_not_outlier

In [2]:
df_data = pd.read_csv("2_datos_no_nulos.csv")

In [3]:
df_data

,sex,age,t2m_pre_mean_rr,t2m_pre_rmssd,t2m_pre_pns,t2m_pre_mean_hr,t2m_pre_stress,t2m_pre_sns,t2m_pre_sdnn,t2m_pre_hf,t2m_pre_lf,t2m_pre_vlf,bp_systolic,bp_diastolic,bp_pam,bp_pp,weight kg,height cm,height mt,our_imc
0,1.0,75.0,74.8,21.7,-140.00,80,149.0,184.00,308.0,222,713,172,108,70,82.666667,38,70.0,160,1.60,27.3437
1,1.0,66.0,95.3,18.8,-54.00,63,145.0,68.00,255.0,87,226,29,122,72,88.666667,50,52.0,149,1.49,23.4224
2,1.0,77.0,81.9,17.5,-106.00,73,249.0,283.00,170.0,118,130,14,126,72,90.000000,54,85.0,160,1.60,33.2031
3,1.0,73.0,84.6,13.6,-115.00,71,166.0,149.00,176.0,66,66,18,130,80,96.666667,50,69.0,151,1.51,30.2618
4,1.0,65.0,129.6,29.8,156.00,46,141.0,-71.00,205.0,236,69,61,129,73,91.666667,56,58.0,149,1.49,26.1249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,2.0,78.0,1187.0,22.2,0.76,51,17.0,0.10,18.8,992,125,30,105,56,72.333333,49,82.2,155,1.55,34.2144
525,2.0,67.0,790.0,16.9,-1.28,76,19.6,2.24,20.0,350,196,88,134,87,102.666667,47,68.1,154,1.54,28.7148
526,2.0,77.0,814.0,23.8,-0.98,74,13.8,1.20,26.7,521,261,39,141,80,100.333333,61,67.1,152,1.52,29.0426
527,2.0,61.0,912.0,16.6,-0.78,66,15.8,1.05,22.4,395,301,27,106,58,74.000000,48,58.4,162,1.62,22.2527
528,2.0,69.0,1016.0,16.9,-0.25,59,18.4,0.97,18.9,604,189,16,111,72,85.000000,39,80.6,180,1.80,24.8765

In [5]:
df_data_outliers = pd.DataFrame()

In [18]:
matrix_data = []

for column in df_data.columns:
    if column != "sex":
        df_data_outliers[column], number_outlier, number_not_outlier = check_outlier_by_column(
            df_data=df_data, 
            column_values=df_data[column].values, 
            name_column=column)
        
        row = [column, number_outlier, number_not_outlier]
        matrix_data.append(row)

df_summary_outliers = pd.DataFrame(data=matrix_data, columns=["column_name", "number_outlier", "number_not_outlier"])

In [25]:
df_data_outliers["outlier_score"] = df_data_outliers.sum(axis=1, numeric_only=True)/(len(df_data.columns)-1)
df_data_outliers

,age,t2m_pre_mean_rr,t2m_pre_rmssd,t2m_pre_pns,t2m_pre_mean_hr,t2m_pre_stress,t2m_pre_sns,t2m_pre_sdnn,t2m_pre_hf,t2m_pre_lf,t2m_pre_vlf,bp_systolic,bp_diastolic,bp_pam,bp_pp,weight kg,height cm,height mt,our_imc,outlier_score
0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.105263
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000
4,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.105263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0.105263
525,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000
526,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000
527,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000
528,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0.210526

In [26]:
df_data_outliers["is_outlier"] = (df_data_outliers["outlier_score"]>0).astype(int)
df_data_outliers["is_outlier"].value_counts()

is_outlier
0    336
1    193
Name: count, dtype: int64

In [22]:
df_data_outliers.T

,0,1,2,3,4,5,6,7,8,9,...,519,520,521,522,523,524,525,526,527,528
age,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t2m_pre_mean_rr,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t2m_pre_rmssd,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t2m_pre_pns,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t2m_pre_mean_hr,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t2m_pre_stress,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t2m_pre_sns,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t2m_pre_sdnn,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t2m_pre_hf,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
t2m_pre_lf,1,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
t2m_pre_vlf,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bp_systolic,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bp_diastolic,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bp_pam,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bp_pp,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
weight kg,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
height cm,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
height mt,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
our_imc,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
df_summary_outliers.sort_values(by="number_outlier", ascending=False)

        column_name  number_outlier  number_not_outlier
9        t2m_pre_lf              76                 453
8        t2m_pre_hf              71                 458
10      t2m_pre_vlf              71                 458
6       t2m_pre_sns              22                 507
15        weight kg              19                 510
2     t2m_pre_rmssd              16                 513
3       t2m_pre_pns              16                 513
16        height cm              13                 516
17        height mt              13                 516
18          our_imc              10                 519
11      bp_systolic               8                 521
13           bp_pam               7                 522
5    t2m_pre_stress               6                 523
14            bp_pp               6                 523
0               age               5                 524
7      t2m_pre_sdnn               5                 524
12     bp_diastolic               3                 526
1   t2m_pre_mean_rr               0                 529
4   t2m_pre_mean_hr               0                 529

In [30]:
clf = IsolationForest(
    random_state = 42
)

clf.fit(df_data)

df_data_outliers["is_outlier_if"] = clf.predict(df_data)

In [32]:
df_data_outliers["is_outlier_if"].value_counts()

is_outlier_if
 1    490
-1     39
Name: count, dtype: int64